package com.example.clubmanage.bean;

public class ActivityMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_member.activity_mamberid
     *
     * @mbggenerated
     */
    private Integer activityMamberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_member.activity_name
     *
     * @mbggenerated
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_member.club_name
     *
     * @mbggenerated
     */
    private String clubName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_member.member_name
     *
     * @mbggenerated
     */
    private String memberName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_member.activity_mamberid
     *
     * @return the value of activity_member.activity_mamberid
     *
     * @mbggenerated
     */
    public Integer getActivityMamberid() {
        return activityMamberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_member.activity_mamberid
     *
     * @param activityMamberid the value for activity_member.activity_mamberid
     *
     * @mbggenerated
     */
    public void setActivityMamberid(Integer activityMamberid) {
        this.activityMamberid = activityMamberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_member.activity_name
     *
     * @return the value of activity_member.activity_name
     *
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_member.activity_name
     *
     * @param activityName the value for activity_member.activity_name
     *
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_member.club_name
     *
     * @return the value of activity_member.club_name
     *
     * @mbggenerated
     */
    public String getClubName() {
        return clubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_member.club_name
     *
     * @param clubName the value for activity_member.club_name
     *
     * @mbggenerated
     */
    public void setClubName(String clubName) {
        this.clubName = clubName == null ? null : clubName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_member.member_name
     *
     * @return the value of activity_member.member_name
     *
     * @mbggenerated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_member.member_name
     *
     * @param memberName the value for activity_member.member_name
     *
     * @mbggenerated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }
}