package com.example.clubmanage.bean;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_name
     *
     * @mbggenerated
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.club
     *
     * @mbggenerated
     */
    private String club;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.start_date
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_date
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_permission
     *
     * @mbggenerated
     */
    private String activityPermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_content
     *
     * @mbggenerated
     */
    private String activityContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.joined_userid
     *
     * @mbggenerated
     */
    private String joinedUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_image
     *
     * @mbggenerated
     */
    private String activityImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_id
     *
     * @return the value of activity.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_id
     *
     * @param activityId the value for activity.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_name
     *
     * @return the value of activity.activity_name
     *
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_name
     *
     * @param activityName the value for activity.activity_name
     *
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.club
     *
     * @return the value of activity.club
     *
     * @mbggenerated
     */
    public String getClub() {
        return club;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.club
     *
     * @param club the value for activity.club
     *
     * @mbggenerated
     */
    public void setClub(String club) {
        this.club = club == null ? null : club.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.start_date
     *
     * @return the value of activity.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.start_date
     *
     * @param startDate the value for activity.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_date
     *
     * @return the value of activity.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_date
     *
     * @param endDate the value for activity.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_permission
     *
     * @return the value of activity.activity_permission
     *
     * @mbggenerated
     */
    public String getActivityPermission() {
        return activityPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_permission
     *
     * @param activityPermission the value for activity.activity_permission
     *
     * @mbggenerated
     */
    public void setActivityPermission(String activityPermission) {
        this.activityPermission = activityPermission == null ? null : activityPermission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_content
     *
     * @return the value of activity.activity_content
     *
     * @mbggenerated
     */
    public String getActivityContent() {
        return activityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_content
     *
     * @param activityContent the value for activity.activity_content
     *
     * @mbggenerated
     */
    public void setActivityContent(String activityContent) {
        this.activityContent = activityContent == null ? null : activityContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.joined_userid
     *
     * @return the value of activity.joined_userid
     *
     * @mbggenerated
     */
    public String getJoinedUserid() {
        return joinedUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.joined_userid
     *
     * @param joinedUserid the value for activity.joined_userid
     *
     * @mbggenerated
     */
    public void setJoinedUserid(String joinedUserid) {
        this.joinedUserid = joinedUserid == null ? null : joinedUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_image
     *
     * @return the value of activity.activity_image
     *
     * @mbggenerated
     */
    public String getActivityImage() {
        return activityImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_image
     *
     * @param activityImage the value for activity.activity_image
     *
     * @mbggenerated
     */
    public void setActivityImage(String activityImage) {
        this.activityImage = activityImage == null ? null : activityImage.trim();
    }
}