package com.example.clubmanage.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ClubExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table club
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table club
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table club
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    public ClubExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table club
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andClubIdIsNull() {
            addCriterion("club_id is null");
            return (Criteria) this;
        }

        public Criteria andClubIdIsNotNull() {
            addCriterion("club_id is not null");
            return (Criteria) this;
        }

        public Criteria andClubIdEqualTo(Integer value) {
            addCriterion("club_id =", value, "clubId");
            return (Criteria) this;
        }

        public Criteria andClubIdNotEqualTo(Integer value) {
            addCriterion("club_id <>", value, "clubId");
            return (Criteria) this;
        }

        public Criteria andClubIdGreaterThan(Integer value) {
            addCriterion("club_id >", value, "clubId");
            return (Criteria) this;
        }

        public Criteria andClubIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("club_id >=", value, "clubId");
            return (Criteria) this;
        }

        public Criteria andClubIdLessThan(Integer value) {
            addCriterion("club_id <", value, "clubId");
            return (Criteria) this;
        }

        public Criteria andClubIdLessThanOrEqualTo(Integer value) {
            addCriterion("club_id <=", value, "clubId");
            return (Criteria) this;
        }

        public Criteria andClubIdIn(List<Integer> values) {
            addCriterion("club_id in", values, "clubId");
            return (Criteria) this;
        }

        public Criteria andClubIdNotIn(List<Integer> values) {
            addCriterion("club_id not in", values, "clubId");
            return (Criteria) this;
        }

        public Criteria andClubIdBetween(Integer value1, Integer value2) {
            addCriterion("club_id between", value1, value2, "clubId");
            return (Criteria) this;
        }

        public Criteria andClubIdNotBetween(Integer value1, Integer value2) {
            addCriterion("club_id not between", value1, value2, "clubId");
            return (Criteria) this;
        }

        public Criteria andClubManagerIsNull() {
            addCriterion("club_manager is null");
            return (Criteria) this;
        }

        public Criteria andClubManagerIsNotNull() {
            addCriterion("club_manager is not null");
            return (Criteria) this;
        }

        public Criteria andClubManagerEqualTo(String value) {
            addCriterion("club_manager =", value, "clubManager");
            return (Criteria) this;
        }

        public Criteria andClubManagerNotEqualTo(String value) {
            addCriterion("club_manager <>", value, "clubManager");
            return (Criteria) this;
        }

        public Criteria andClubManagerGreaterThan(String value) {
            addCriterion("club_manager >", value, "clubManager");
            return (Criteria) this;
        }

        public Criteria andClubManagerGreaterThanOrEqualTo(String value) {
            addCriterion("club_manager >=", value, "clubManager");
            return (Criteria) this;
        }

        public Criteria andClubManagerLessThan(String value) {
            addCriterion("club_manager <", value, "clubManager");
            return (Criteria) this;
        }

        public Criteria andClubManagerLessThanOrEqualTo(String value) {
            addCriterion("club_manager <=", value, "clubManager");
            return (Criteria) this;
        }

        public Criteria andClubManagerLike(String value) {
            addCriterion("club_manager like", value, "clubManager");
            return (Criteria) this;
        }

        public Criteria andClubManagerNotLike(String value) {
            addCriterion("club_manager not like", value, "clubManager");
            return (Criteria) this;
        }

        public Criteria andClubManagerIn(List<String> values) {
            addCriterion("club_manager in", values, "clubManager");
            return (Criteria) this;
        }

        public Criteria andClubManagerNotIn(List<String> values) {
            addCriterion("club_manager not in", values, "clubManager");
            return (Criteria) this;
        }

        public Criteria andClubManagerBetween(String value1, String value2) {
            addCriterion("club_manager between", value1, value2, "clubManager");
            return (Criteria) this;
        }

        public Criteria andClubManagerNotBetween(String value1, String value2) {
            addCriterion("club_manager not between", value1, value2, "clubManager");
            return (Criteria) this;
        }

        public Criteria andClubNameIsNull() {
            addCriterion("club_name is null");
            return (Criteria) this;
        }

        public Criteria andClubNameIsNotNull() {
            addCriterion("club_name is not null");
            return (Criteria) this;
        }

        public Criteria andClubNameEqualTo(String value) {
            addCriterion("club_name =", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameNotEqualTo(String value) {
            addCriterion("club_name <>", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameGreaterThan(String value) {
            addCriterion("club_name >", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameGreaterThanOrEqualTo(String value) {
            addCriterion("club_name >=", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameLessThan(String value) {
            addCriterion("club_name <", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameLessThanOrEqualTo(String value) {
            addCriterion("club_name <=", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameLike(String value) {
            addCriterion("club_name like", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameNotLike(String value) {
            addCriterion("club_name not like", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameIn(List<String> values) {
            addCriterion("club_name in", values, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameNotIn(List<String> values) {
            addCriterion("club_name not in", values, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameBetween(String value1, String value2) {
            addCriterion("club_name between", value1, value2, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameNotBetween(String value1, String value2) {
            addCriterion("club_name not between", value1, value2, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubCreatdateIsNull() {
            addCriterion("club_creatdate is null");
            return (Criteria) this;
        }

        public Criteria andClubCreatdateIsNotNull() {
            addCriterion("club_creatdate is not null");
            return (Criteria) this;
        }

        public Criteria andClubCreatdateEqualTo(Date value) {
            addCriterionForJDBCDate("club_creatdate =", value, "clubCreatdate");
            return (Criteria) this;
        }

        public Criteria andClubCreatdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("club_creatdate <>", value, "clubCreatdate");
            return (Criteria) this;
        }

        public Criteria andClubCreatdateGreaterThan(Date value) {
            addCriterionForJDBCDate("club_creatdate >", value, "clubCreatdate");
            return (Criteria) this;
        }

        public Criteria andClubCreatdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("club_creatdate >=", value, "clubCreatdate");
            return (Criteria) this;
        }

        public Criteria andClubCreatdateLessThan(Date value) {
            addCriterionForJDBCDate("club_creatdate <", value, "clubCreatdate");
            return (Criteria) this;
        }

        public Criteria andClubCreatdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("club_creatdate <=", value, "clubCreatdate");
            return (Criteria) this;
        }

        public Criteria andClubCreatdateIn(List<Date> values) {
            addCriterionForJDBCDate("club_creatdate in", values, "clubCreatdate");
            return (Criteria) this;
        }

        public Criteria andClubCreatdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("club_creatdate not in", values, "clubCreatdate");
            return (Criteria) this;
        }

        public Criteria andClubCreatdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("club_creatdate between", value1, value2, "clubCreatdate");
            return (Criteria) this;
        }

        public Criteria andClubCreatdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("club_creatdate not between", value1, value2, "clubCreatdate");
            return (Criteria) this;
        }

        public Criteria andManagerNumIsNull() {
            addCriterion("manager_num is null");
            return (Criteria) this;
        }

        public Criteria andManagerNumIsNotNull() {
            addCriterion("manager_num is not null");
            return (Criteria) this;
        }

        public Criteria andManagerNumEqualTo(Integer value) {
            addCriterion("manager_num =", value, "managerNum");
            return (Criteria) this;
        }

        public Criteria andManagerNumNotEqualTo(Integer value) {
            addCriterion("manager_num <>", value, "managerNum");
            return (Criteria) this;
        }

        public Criteria andManagerNumGreaterThan(Integer value) {
            addCriterion("manager_num >", value, "managerNum");
            return (Criteria) this;
        }

        public Criteria andManagerNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("manager_num >=", value, "managerNum");
            return (Criteria) this;
        }

        public Criteria andManagerNumLessThan(Integer value) {
            addCriterion("manager_num <", value, "managerNum");
            return (Criteria) this;
        }

        public Criteria andManagerNumLessThanOrEqualTo(Integer value) {
            addCriterion("manager_num <=", value, "managerNum");
            return (Criteria) this;
        }

        public Criteria andManagerNumIn(List<Integer> values) {
            addCriterion("manager_num in", values, "managerNum");
            return (Criteria) this;
        }

        public Criteria andManagerNumNotIn(List<Integer> values) {
            addCriterion("manager_num not in", values, "managerNum");
            return (Criteria) this;
        }

        public Criteria andManagerNumBetween(Integer value1, Integer value2) {
            addCriterion("manager_num between", value1, value2, "managerNum");
            return (Criteria) this;
        }

        public Criteria andManagerNumNotBetween(Integer value1, Integer value2) {
            addCriterion("manager_num not between", value1, value2, "managerNum");
            return (Criteria) this;
        }

        public Criteria andClubClassIsNull() {
            addCriterion("club_class is null");
            return (Criteria) this;
        }

        public Criteria andClubClassIsNotNull() {
            addCriterion("club_class is not null");
            return (Criteria) this;
        }

        public Criteria andClubClassEqualTo(Integer value) {
            addCriterion("club_class =", value, "clubClass");
            return (Criteria) this;
        }

        public Criteria andClubClassNotEqualTo(Integer value) {
            addCriterion("club_class <>", value, "clubClass");
            return (Criteria) this;
        }

        public Criteria andClubClassGreaterThan(Integer value) {
            addCriterion("club_class >", value, "clubClass");
            return (Criteria) this;
        }

        public Criteria andClubClassGreaterThanOrEqualTo(Integer value) {
            addCriterion("club_class >=", value, "clubClass");
            return (Criteria) this;
        }

        public Criteria andClubClassLessThan(Integer value) {
            addCriterion("club_class <", value, "clubClass");
            return (Criteria) this;
        }

        public Criteria andClubClassLessThanOrEqualTo(Integer value) {
            addCriterion("club_class <=", value, "clubClass");
            return (Criteria) this;
        }

        public Criteria andClubClassIn(List<Integer> values) {
            addCriterion("club_class in", values, "clubClass");
            return (Criteria) this;
        }

        public Criteria andClubClassNotIn(List<Integer> values) {
            addCriterion("club_class not in", values, "clubClass");
            return (Criteria) this;
        }

        public Criteria andClubClassBetween(Integer value1, Integer value2) {
            addCriterion("club_class between", value1, value2, "clubClass");
            return (Criteria) this;
        }

        public Criteria andClubClassNotBetween(Integer value1, Integer value2) {
            addCriterion("club_class not between", value1, value2, "clubClass");
            return (Criteria) this;
        }

        public Criteria andClubTenetIsNull() {
            addCriterion("club_tenet is null");
            return (Criteria) this;
        }

        public Criteria andClubTenetIsNotNull() {
            addCriterion("club_tenet is not null");
            return (Criteria) this;
        }

        public Criteria andClubTenetEqualTo(String value) {
            addCriterion("club_tenet =", value, "clubTenet");
            return (Criteria) this;
        }

        public Criteria andClubTenetNotEqualTo(String value) {
            addCriterion("club_tenet <>", value, "clubTenet");
            return (Criteria) this;
        }

        public Criteria andClubTenetGreaterThan(String value) {
            addCriterion("club_tenet >", value, "clubTenet");
            return (Criteria) this;
        }

        public Criteria andClubTenetGreaterThanOrEqualTo(String value) {
            addCriterion("club_tenet >=", value, "clubTenet");
            return (Criteria) this;
        }

        public Criteria andClubTenetLessThan(String value) {
            addCriterion("club_tenet <", value, "clubTenet");
            return (Criteria) this;
        }

        public Criteria andClubTenetLessThanOrEqualTo(String value) {
            addCriterion("club_tenet <=", value, "clubTenet");
            return (Criteria) this;
        }

        public Criteria andClubTenetLike(String value) {
            addCriterion("club_tenet like", value, "clubTenet");
            return (Criteria) this;
        }

        public Criteria andClubTenetNotLike(String value) {
            addCriterion("club_tenet not like", value, "clubTenet");
            return (Criteria) this;
        }

        public Criteria andClubTenetIn(List<String> values) {
            addCriterion("club_tenet in", values, "clubTenet");
            return (Criteria) this;
        }

        public Criteria andClubTenetNotIn(List<String> values) {
            addCriterion("club_tenet not in", values, "clubTenet");
            return (Criteria) this;
        }

        public Criteria andClubTenetBetween(String value1, String value2) {
            addCriterion("club_tenet between", value1, value2, "clubTenet");
            return (Criteria) this;
        }

        public Criteria andClubTenetNotBetween(String value1, String value2) {
            addCriterion("club_tenet not between", value1, value2, "clubTenet");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionIsNull() {
            addCriterion("club_introduction is null");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionIsNotNull() {
            addCriterion("club_introduction is not null");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionEqualTo(String value) {
            addCriterion("club_introduction =", value, "clubIntroduction");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionNotEqualTo(String value) {
            addCriterion("club_introduction <>", value, "clubIntroduction");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionGreaterThan(String value) {
            addCriterion("club_introduction >", value, "clubIntroduction");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("club_introduction >=", value, "clubIntroduction");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionLessThan(String value) {
            addCriterion("club_introduction <", value, "clubIntroduction");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionLessThanOrEqualTo(String value) {
            addCriterion("club_introduction <=", value, "clubIntroduction");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionLike(String value) {
            addCriterion("club_introduction like", value, "clubIntroduction");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionNotLike(String value) {
            addCriterion("club_introduction not like", value, "clubIntroduction");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionIn(List<String> values) {
            addCriterion("club_introduction in", values, "clubIntroduction");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionNotIn(List<String> values) {
            addCriterion("club_introduction not in", values, "clubIntroduction");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionBetween(String value1, String value2) {
            addCriterion("club_introduction between", value1, value2, "clubIntroduction");
            return (Criteria) this;
        }

        public Criteria andClubIntroductionNotBetween(String value1, String value2) {
            addCriterion("club_introduction not between", value1, value2, "clubIntroduction");
            return (Criteria) this;
        }

        public Criteria andClubImagepathIsNull() {
            addCriterion("club_imagepath is null");
            return (Criteria) this;
        }

        public Criteria andClubImagepathIsNotNull() {
            addCriterion("club_imagepath is not null");
            return (Criteria) this;
        }

        public Criteria andClubImagepathEqualTo(String value) {
            addCriterion("club_imagepath =", value, "clubImagepath");
            return (Criteria) this;
        }

        public Criteria andClubImagepathNotEqualTo(String value) {
            addCriterion("club_imagepath <>", value, "clubImagepath");
            return (Criteria) this;
        }

        public Criteria andClubImagepathGreaterThan(String value) {
            addCriterion("club_imagepath >", value, "clubImagepath");
            return (Criteria) this;
        }

        public Criteria andClubImagepathGreaterThanOrEqualTo(String value) {
            addCriterion("club_imagepath >=", value, "clubImagepath");
            return (Criteria) this;
        }

        public Criteria andClubImagepathLessThan(String value) {
            addCriterion("club_imagepath <", value, "clubImagepath");
            return (Criteria) this;
        }

        public Criteria andClubImagepathLessThanOrEqualTo(String value) {
            addCriterion("club_imagepath <=", value, "clubImagepath");
            return (Criteria) this;
        }

        public Criteria andClubImagepathLike(String value) {
            addCriterion("club_imagepath like", value, "clubImagepath");
            return (Criteria) this;
        }

        public Criteria andClubImagepathNotLike(String value) {
            addCriterion("club_imagepath not like", value, "clubImagepath");
            return (Criteria) this;
        }

        public Criteria andClubImagepathIn(List<String> values) {
            addCriterion("club_imagepath in", values, "clubImagepath");
            return (Criteria) this;
        }

        public Criteria andClubImagepathNotIn(List<String> values) {
            addCriterion("club_imagepath not in", values, "clubImagepath");
            return (Criteria) this;
        }

        public Criteria andClubImagepathBetween(String value1, String value2) {
            addCriterion("club_imagepath between", value1, value2, "clubImagepath");
            return (Criteria) this;
        }

        public Criteria andClubImagepathNotBetween(String value1, String value2) {
            addCriterion("club_imagepath not between", value1, value2, "clubImagepath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table club
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table club
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}