package com.example.clubmanage.bean;

import java.util.Date;

public class ClubCreat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_creat.clubcreat_id
     *
     * @mbggenerated
     */
    private Integer clubcreatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_creat.club_manager
     *
     * @mbggenerated
     */
    private String clubManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_creat.club_name
     *
     * @mbggenerated
     */
    private String clubName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_creat.application_date
     *
     * @mbggenerated
     */
    private Date applicationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_creat.max_number
     *
     * @mbggenerated
     */
    private Integer maxNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_creat.club_class
     *
     * @mbggenerated
     */
    private Integer clubClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_creat.club_tenet
     *
     * @mbggenerated
     */
    private String clubTenet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_creat.club_introduction
     *
     * @mbggenerated
     */
    private String clubIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_creat.club_imagepath
     *
     * @mbggenerated
     */
    private String clubImagepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_creat.club_creatstate
     *
     * @mbggenerated
     */
    private Integer clubCreatstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_creat.clubcreat_id
     *
     * @return the value of club_creat.clubcreat_id
     *
     * @mbggenerated
     */
    public Integer getClubcreatId() {
        return clubcreatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_creat.clubcreat_id
     *
     * @param clubcreatId the value for club_creat.clubcreat_id
     *
     * @mbggenerated
     */
    public void setClubcreatId(Integer clubcreatId) {
        this.clubcreatId = clubcreatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_creat.club_manager
     *
     * @return the value of club_creat.club_manager
     *
     * @mbggenerated
     */
    public String getClubManager() {
        return clubManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_creat.club_manager
     *
     * @param clubManager the value for club_creat.club_manager
     *
     * @mbggenerated
     */
    public void setClubManager(String clubManager) {
        this.clubManager = clubManager == null ? null : clubManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_creat.club_name
     *
     * @return the value of club_creat.club_name
     *
     * @mbggenerated
     */
    public String getClubName() {
        return clubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_creat.club_name
     *
     * @param clubName the value for club_creat.club_name
     *
     * @mbggenerated
     */
    public void setClubName(String clubName) {
        this.clubName = clubName == null ? null : clubName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_creat.application_date
     *
     * @return the value of club_creat.application_date
     *
     * @mbggenerated
     */
    public Date getApplicationDate() {
        return applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_creat.application_date
     *
     * @param applicationDate the value for club_creat.application_date
     *
     * @mbggenerated
     */
    public void setApplicationDate(Date applicationDate) {
        this.applicationDate = applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_creat.max_number
     *
     * @return the value of club_creat.max_number
     *
     * @mbggenerated
     */
    public Integer getMaxNumber() {
        return maxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_creat.max_number
     *
     * @param maxNumber the value for club_creat.max_number
     *
     * @mbggenerated
     */
    public void setMaxNumber(Integer maxNumber) {
        this.maxNumber = maxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_creat.club_class
     *
     * @return the value of club_creat.club_class
     *
     * @mbggenerated
     */
    public Integer getClubClass() {
        return clubClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_creat.club_class
     *
     * @param clubClass the value for club_creat.club_class
     *
     * @mbggenerated
     */
    public void setClubClass(Integer clubClass) {
        this.clubClass = clubClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_creat.club_tenet
     *
     * @return the value of club_creat.club_tenet
     *
     * @mbggenerated
     */
    public String getClubTenet() {
        return clubTenet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_creat.club_tenet
     *
     * @param clubTenet the value for club_creat.club_tenet
     *
     * @mbggenerated
     */
    public void setClubTenet(String clubTenet) {
        this.clubTenet = clubTenet == null ? null : clubTenet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_creat.club_introduction
     *
     * @return the value of club_creat.club_introduction
     *
     * @mbggenerated
     */
    public String getClubIntroduction() {
        return clubIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_creat.club_introduction
     *
     * @param clubIntroduction the value for club_creat.club_introduction
     *
     * @mbggenerated
     */
    public void setClubIntroduction(String clubIntroduction) {
        this.clubIntroduction = clubIntroduction == null ? null : clubIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_creat.club_imagepath
     *
     * @return the value of club_creat.club_imagepath
     *
     * @mbggenerated
     */
    public String getClubImagepath() {
        return clubImagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_creat.club_imagepath
     *
     * @param clubImagepath the value for club_creat.club_imagepath
     *
     * @mbggenerated
     */
    public void setClubImagepath(String clubImagepath) {
        this.clubImagepath = clubImagepath == null ? null : clubImagepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_creat.club_creatstate
     *
     * @return the value of club_creat.club_creatstate
     *
     * @mbggenerated
     */
    public Integer getClubCreatstate() {
        return clubCreatstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_creat.club_creatstate
     *
     * @param clubCreatstate the value for club_creat.club_creatstate
     *
     * @mbggenerated
     */
    public void setClubCreatstate(Integer clubCreatstate) {
        this.clubCreatstate = clubCreatstate;
    }
}