package com.example.clubmanage.bean;

public class ClubMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_member.clubmember_id
     *
     * @mbggenerated
     */
    private Integer clubmemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_member.club_name
     *
     * @mbggenerated
     */
    private String clubName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_member.clubmember_name
     *
     * @mbggenerated
     */
    private String clubmemberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_member.member_stuid
     *
     * @mbggenerated
     */
    private String memberStuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_member.member_phone
     *
     * @mbggenerated
     */
    private String memberPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_member.clubmember_id
     *
     * @return the value of club_member.clubmember_id
     *
     * @mbggenerated
     */
    public Integer getClubmemberId() {
        return clubmemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_member.clubmember_id
     *
     * @param clubmemberId the value for club_member.clubmember_id
     *
     * @mbggenerated
     */
    public void setClubmemberId(Integer clubmemberId) {
        this.clubmemberId = clubmemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_member.club_name
     *
     * @return the value of club_member.club_name
     *
     * @mbggenerated
     */
    public String getClubName() {
        return clubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_member.club_name
     *
     * @param clubName the value for club_member.club_name
     *
     * @mbggenerated
     */
    public void setClubName(String clubName) {
        this.clubName = clubName == null ? null : clubName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_member.clubmember_name
     *
     * @return the value of club_member.clubmember_name
     *
     * @mbggenerated
     */
    public String getClubmemberName() {
        return clubmemberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_member.clubmember_name
     *
     * @param clubmemberName the value for club_member.clubmember_name
     *
     * @mbggenerated
     */
    public void setClubmemberName(String clubmemberName) {
        this.clubmemberName = clubmemberName == null ? null : clubmemberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_member.member_stuid
     *
     * @return the value of club_member.member_stuid
     *
     * @mbggenerated
     */
    public String getMemberStuid() {
        return memberStuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_member.member_stuid
     *
     * @param memberStuid the value for club_member.member_stuid
     *
     * @mbggenerated
     */
    public void setMemberStuid(String memberStuid) {
        this.memberStuid = memberStuid == null ? null : memberStuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_member.member_phone
     *
     * @return the value of club_member.member_phone
     *
     * @mbggenerated
     */
    public String getMemberPhone() {
        return memberPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_member.member_phone
     *
     * @param memberPhone the value for club_member.member_phone
     *
     * @mbggenerated
     */
    public void setMemberPhone(String memberPhone) {
        this.memberPhone = memberPhone == null ? null : memberPhone.trim();
    }
}