package com.example.clubmanage.bean;

import java.util.ArrayList;
import java.util.List;

public class ClubMemberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table club_member
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table club_member
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table club_member
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    public ClubMemberExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table club_member
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClubmemberIdIsNull() {
            addCriterion("clubmember_id is null");
            return (Criteria) this;
        }

        public Criteria andClubmemberIdIsNotNull() {
            addCriterion("clubmember_id is not null");
            return (Criteria) this;
        }

        public Criteria andClubmemberIdEqualTo(Integer value) {
            addCriterion("clubmember_id =", value, "clubmemberId");
            return (Criteria) this;
        }

        public Criteria andClubmemberIdNotEqualTo(Integer value) {
            addCriterion("clubmember_id <>", value, "clubmemberId");
            return (Criteria) this;
        }

        public Criteria andClubmemberIdGreaterThan(Integer value) {
            addCriterion("clubmember_id >", value, "clubmemberId");
            return (Criteria) this;
        }

        public Criteria andClubmemberIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("clubmember_id >=", value, "clubmemberId");
            return (Criteria) this;
        }

        public Criteria andClubmemberIdLessThan(Integer value) {
            addCriterion("clubmember_id <", value, "clubmemberId");
            return (Criteria) this;
        }

        public Criteria andClubmemberIdLessThanOrEqualTo(Integer value) {
            addCriterion("clubmember_id <=", value, "clubmemberId");
            return (Criteria) this;
        }

        public Criteria andClubmemberIdIn(List<Integer> values) {
            addCriterion("clubmember_id in", values, "clubmemberId");
            return (Criteria) this;
        }

        public Criteria andClubmemberIdNotIn(List<Integer> values) {
            addCriterion("clubmember_id not in", values, "clubmemberId");
            return (Criteria) this;
        }

        public Criteria andClubmemberIdBetween(Integer value1, Integer value2) {
            addCriterion("clubmember_id between", value1, value2, "clubmemberId");
            return (Criteria) this;
        }

        public Criteria andClubmemberIdNotBetween(Integer value1, Integer value2) {
            addCriterion("clubmember_id not between", value1, value2, "clubmemberId");
            return (Criteria) this;
        }

        public Criteria andClubNameIsNull() {
            addCriterion("club_name is null");
            return (Criteria) this;
        }

        public Criteria andClubNameIsNotNull() {
            addCriterion("club_name is not null");
            return (Criteria) this;
        }

        public Criteria andClubNameEqualTo(String value) {
            addCriterion("club_name =", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameNotEqualTo(String value) {
            addCriterion("club_name <>", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameGreaterThan(String value) {
            addCriterion("club_name >", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameGreaterThanOrEqualTo(String value) {
            addCriterion("club_name >=", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameLessThan(String value) {
            addCriterion("club_name <", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameLessThanOrEqualTo(String value) {
            addCriterion("club_name <=", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameLike(String value) {
            addCriterion("club_name like", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameNotLike(String value) {
            addCriterion("club_name not like", value, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameIn(List<String> values) {
            addCriterion("club_name in", values, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameNotIn(List<String> values) {
            addCriterion("club_name not in", values, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameBetween(String value1, String value2) {
            addCriterion("club_name between", value1, value2, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubNameNotBetween(String value1, String value2) {
            addCriterion("club_name not between", value1, value2, "clubName");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameIsNull() {
            addCriterion("clubmember_name is null");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameIsNotNull() {
            addCriterion("clubmember_name is not null");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameEqualTo(String value) {
            addCriterion("clubmember_name =", value, "clubmemberName");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameNotEqualTo(String value) {
            addCriterion("clubmember_name <>", value, "clubmemberName");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameGreaterThan(String value) {
            addCriterion("clubmember_name >", value, "clubmemberName");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameGreaterThanOrEqualTo(String value) {
            addCriterion("clubmember_name >=", value, "clubmemberName");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameLessThan(String value) {
            addCriterion("clubmember_name <", value, "clubmemberName");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameLessThanOrEqualTo(String value) {
            addCriterion("clubmember_name <=", value, "clubmemberName");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameLike(String value) {
            addCriterion("clubmember_name like", value, "clubmemberName");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameNotLike(String value) {
            addCriterion("clubmember_name not like", value, "clubmemberName");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameIn(List<String> values) {
            addCriterion("clubmember_name in", values, "clubmemberName");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameNotIn(List<String> values) {
            addCriterion("clubmember_name not in", values, "clubmemberName");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameBetween(String value1, String value2) {
            addCriterion("clubmember_name between", value1, value2, "clubmemberName");
            return (Criteria) this;
        }

        public Criteria andClubmemberNameNotBetween(String value1, String value2) {
            addCriterion("clubmember_name not between", value1, value2, "clubmemberName");
            return (Criteria) this;
        }

        public Criteria andMemberStuidIsNull() {
            addCriterion("member_stuid is null");
            return (Criteria) this;
        }

        public Criteria andMemberStuidIsNotNull() {
            addCriterion("member_stuid is not null");
            return (Criteria) this;
        }

        public Criteria andMemberStuidEqualTo(String value) {
            addCriterion("member_stuid =", value, "memberStuid");
            return (Criteria) this;
        }

        public Criteria andMemberStuidNotEqualTo(String value) {
            addCriterion("member_stuid <>", value, "memberStuid");
            return (Criteria) this;
        }

        public Criteria andMemberStuidGreaterThan(String value) {
            addCriterion("member_stuid >", value, "memberStuid");
            return (Criteria) this;
        }

        public Criteria andMemberStuidGreaterThanOrEqualTo(String value) {
            addCriterion("member_stuid >=", value, "memberStuid");
            return (Criteria) this;
        }

        public Criteria andMemberStuidLessThan(String value) {
            addCriterion("member_stuid <", value, "memberStuid");
            return (Criteria) this;
        }

        public Criteria andMemberStuidLessThanOrEqualTo(String value) {
            addCriterion("member_stuid <=", value, "memberStuid");
            return (Criteria) this;
        }

        public Criteria andMemberStuidLike(String value) {
            addCriterion("member_stuid like", value, "memberStuid");
            return (Criteria) this;
        }

        public Criteria andMemberStuidNotLike(String value) {
            addCriterion("member_stuid not like", value, "memberStuid");
            return (Criteria) this;
        }

        public Criteria andMemberStuidIn(List<String> values) {
            addCriterion("member_stuid in", values, "memberStuid");
            return (Criteria) this;
        }

        public Criteria andMemberStuidNotIn(List<String> values) {
            addCriterion("member_stuid not in", values, "memberStuid");
            return (Criteria) this;
        }

        public Criteria andMemberStuidBetween(String value1, String value2) {
            addCriterion("member_stuid between", value1, value2, "memberStuid");
            return (Criteria) this;
        }

        public Criteria andMemberStuidNotBetween(String value1, String value2) {
            addCriterion("member_stuid not between", value1, value2, "memberStuid");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneIsNull() {
            addCriterion("member_phone is null");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneIsNotNull() {
            addCriterion("member_phone is not null");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneEqualTo(String value) {
            addCriterion("member_phone =", value, "memberPhone");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneNotEqualTo(String value) {
            addCriterion("member_phone <>", value, "memberPhone");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneGreaterThan(String value) {
            addCriterion("member_phone >", value, "memberPhone");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("member_phone >=", value, "memberPhone");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneLessThan(String value) {
            addCriterion("member_phone <", value, "memberPhone");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneLessThanOrEqualTo(String value) {
            addCriterion("member_phone <=", value, "memberPhone");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneLike(String value) {
            addCriterion("member_phone like", value, "memberPhone");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneNotLike(String value) {
            addCriterion("member_phone not like", value, "memberPhone");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneIn(List<String> values) {
            addCriterion("member_phone in", values, "memberPhone");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneNotIn(List<String> values) {
            addCriterion("member_phone not in", values, "memberPhone");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneBetween(String value1, String value2) {
            addCriterion("member_phone between", value1, value2, "memberPhone");
            return (Criteria) this;
        }

        public Criteria andMemberPhoneNotBetween(String value1, String value2) {
            addCriterion("member_phone not between", value1, value2, "memberPhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table club_member
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table club_member
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}