package com.example.clubmanage.bean;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Club {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.club_id
     *
     * @mbggenerated
     */
    private Integer clubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.club_manager
     *
     * @mbggenerated
     */
    private String clubManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.club_name
     *
     * @mbggenerated
     */
    private String clubName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.club_creatdate
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date clubCreatdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.manager_num
     *
     * @mbggenerated
     */
    private Integer managerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.club_class
     *
     * @mbggenerated
     */
    private Integer clubClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.club_tenet
     *
     * @mbggenerated
     */
    private String clubTenet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.club_introduction
     *
     * @mbggenerated
     */
    private String clubIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.club_imagepath
     *
     * @mbggenerated
     */
    private String clubImagepath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.club_id
     *
     * @return the value of club.club_id
     *
     * @mbggenerated
     */
    public Integer getClubId() {
        return clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.club_id
     *
     * @param clubId the value for club.club_id
     *
     * @mbggenerated
     */
    public void setClubId(Integer clubId) {
        this.clubId = clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.club_manager
     *
     * @return the value of club.club_manager
     *
     * @mbggenerated
     */
    public String getClubManager() {
        return clubManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.club_manager
     *
     * @param clubManager the value for club.club_manager
     *
     * @mbggenerated
     */
    public void setClubManager(String clubManager) {
        this.clubManager = clubManager == null ? null : clubManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.club_name
     *
     * @return the value of club.club_name
     *
     * @mbggenerated
     */
    public String getClubName() {
        return clubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.club_name
     *
     * @param clubName the value for club.club_name
     *
     * @mbggenerated
     */
    public void setClubName(String clubName) {
        this.clubName = clubName == null ? null : clubName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.club_creatdate
     *
     * @return the value of club.club_creatdate
     *
     * @mbggenerated
     */
    public Date getClubCreatdate() {
        return clubCreatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.club_creatdate
     *
     * @param clubCreatdate the value for club.club_creatdate
     *
     * @mbggenerated
     */
    public void setClubCreatdate(Date clubCreatdate) {
        this.clubCreatdate = clubCreatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.manager_num
     *
     * @return the value of club.manager_num
     *
     * @mbggenerated
     */
    public Integer getManagerNum() {
        return managerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.manager_num
     *
     * @param managerNum the value for club.manager_num
     *
     * @mbggenerated
     */
    public void setManagerNum(Integer managerNum) {
        this.managerNum = managerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.club_class
     *
     * @return the value of club.club_class
     *
     * @mbggenerated
     */
    public Integer getClubClass() {
        return clubClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.club_class
     *
     * @param clubClass the value for club.club_class
     *
     * @mbggenerated
     */
    public void setClubClass(Integer clubClass) {
        this.clubClass = clubClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.club_tenet
     *
     * @return the value of club.club_tenet
     *
     * @mbggenerated
     */
    public String getClubTenet() {
        return clubTenet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.club_tenet
     *
     * @param clubTenet the value for club.club_tenet
     *
     * @mbggenerated
     */
    public void setClubTenet(String clubTenet) {
        this.clubTenet = clubTenet == null ? null : clubTenet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.club_introduction
     *
     * @return the value of club.club_introduction
     *
     * @mbggenerated
     */
    public String getClubIntroduction() {
        return clubIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.club_introduction
     *
     * @param clubIntroduction the value for club.club_introduction
     *
     * @mbggenerated
     */
    public void setClubIntroduction(String clubIntroduction) {
        this.clubIntroduction = clubIntroduction == null ? null : clubIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.club_imagepath
     *
     * @return the value of club.club_imagepath
     *
     * @mbggenerated
     */
    public String getClubImagepath() {
        return clubImagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.club_imagepath
     *
     * @param clubImagepath the value for club.club_imagepath
     *
     * @mbggenerated
     */
    public void setClubImagepath(String clubImagepath) {
        this.clubImagepath = clubImagepath == null ? null : clubImagepath.trim();
    }
}