package com.example.clubmanage.bean;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_id
     *
     * @mbggenerated
     */
    private Integer noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.club_name
     *
     * @mbggenerated
     */
    private String clubName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_date
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date noticeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_content
     *
     * @mbggenerated
     */
    private String noticeContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_id
     *
     * @return the value of notice.notice_id
     *
     * @mbggenerated
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_id
     *
     * @param noticeId the value for notice.notice_id
     *
     * @mbggenerated
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.club_name
     *
     * @return the value of notice.club_name
     *
     * @mbggenerated
     */
    public String getClubName() {
        return clubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.club_name
     *
     * @param clubName the value for notice.club_name
     *
     * @mbggenerated
     */
    public void setClubName(String clubName) {
        this.clubName = clubName == null ? null : clubName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_date
     *
     * @return the value of notice.notice_date
     *
     * @mbggenerated
     */
    public Date getNoticeDate() {
        return noticeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_date
     *
     * @param noticeDate the value for notice.notice_date
     *
     * @mbggenerated
     */
    public void setNoticeDate(Date noticeDate) {
        this.noticeDate = noticeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_content
     *
     * @return the value of notice.notice_content
     *
     * @mbggenerated
     */
    public String getNoticeContent() {
        return noticeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_content
     *
     * @param noticeContent the value for notice.notice_content
     *
     * @mbggenerated
     */
    public void setNoticeContent(String noticeContent) {
        this.noticeContent = noticeContent == null ? null : noticeContent.trim();
    }
}