package com.example.clubmanage.bean;

import cn.afterturn.easypoi.excel.annotation.Excel;

public class Student implements java.io.Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbggenerated
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_nameid
     *
     * @mbggenerated
     */
    @Excel(name = "学号")
    private String studentNameid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade
     *
     * @mbggenerated
     */
    @Excel(name = "年纪")
    private String grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_nameid
     *
     * @return the value of student.student_nameid
     *
     * @mbggenerated
     */
    public String getStudentNameid() {
        return studentNameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_nameid
     *
     * @param studentNameid the value for student.student_nameid
     *
     * @mbggenerated
     */
    public void setStudentNameid(String studentNameid) {
        this.studentNameid = studentNameid == null ? null : studentNameid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade
     *
     * @return the value of student.grade
     *
     * @mbggenerated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade
     *
     * @param grade the value for student.grade
     *
     * @mbggenerated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    public Student() {
    }
}