package com.example.clubmanage.bean;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_pass
     *
     * @mbggenerated
     */
    private String userPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.student_id
     *
     * @mbggenerated
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.manage_id
     *
     * @mbggenerated
     */
    private String manageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.grade
     *
     * @mbggenerated
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.college
     *
     * @mbggenerated
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.joined_club
     *
     * @mbggenerated
     */
    private String joinedClub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_imagepath
     *
     * @mbggenerated
     */
    private String userImagepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.club_manager
     *
     * @mbggenerated
     */
    private Integer clubManager;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_pass
     *
     * @return the value of user.user_pass
     *
     * @mbggenerated
     */
    public String getUserPass() {
        return userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_pass
     *
     * @param userPass the value for user.user_pass
     *
     * @mbggenerated
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass == null ? null : userPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.student_id
     *
     * @return the value of user.student_id
     *
     * @mbggenerated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.student_id
     *
     * @param studentId the value for user.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.manage_id
     *
     * @return the value of user.manage_id
     *
     * @mbggenerated
     */
    public String getManageId() {
        return manageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.manage_id
     *
     * @param manageId the value for user.manage_id
     *
     * @mbggenerated
     */
    public void setManageId(String manageId) {
        this.manageId = manageId == null ? null : manageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.grade
     *
     * @return the value of user.grade
     *
     * @mbggenerated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.grade
     *
     * @param grade the value for user.grade
     *
     * @mbggenerated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.college
     *
     * @return the value of user.college
     *
     * @mbggenerated
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.college
     *
     * @param college the value for user.college
     *
     * @mbggenerated
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.joined_club
     *
     * @return the value of user.joined_club
     *
     * @mbggenerated
     */
    public String getJoinedClub() {
        return joinedClub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.joined_club
     *
     * @param joinedClub the value for user.joined_club
     *
     * @mbggenerated
     */
    public void setJoinedClub(String joinedClub) {
        this.joinedClub = joinedClub == null ? null : joinedClub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_imagepath
     *
     * @return the value of user.user_imagepath
     *
     * @mbggenerated
     */
    public String getUserImagepath() {
        return userImagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_imagepath
     *
     * @param userImagepath the value for user.user_imagepath
     *
     * @mbggenerated
     */
    public void setUserImagepath(String userImagepath) {
        this.userImagepath = userImagepath == null ? null : userImagepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.club_manager
     *
     * @return the value of user.club_manager
     *
     * @mbggenerated
     */
    public Integer getClubManager() {
        return clubManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.club_manager
     *
     * @param clubManager the value for user.club_manager
     *
     * @mbggenerated
     */
    public void setClubManager(Integer clubManager) {
        this.clubManager = clubManager;
    }
}