package com.example.clubmanage.bean;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Vote {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.vote_id
     *
     * @mbggenerated
     */
    private Integer voteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.start_date
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.end_date
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.joined_number
     *
     * @mbggenerated
     */
    private Integer joinedNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.yes_number
     *
     * @mbggenerated
     */
    private Integer yesNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.vote_creatstate
     *
     * @mbggenerated
     */
    private Integer voteCreatstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.vote_content
     *
     * @mbggenerated
     */
    private String voteContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.vote_yesitem
     *
     * @mbggenerated
     */
    private String voteYesitem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.vote_noitem
     *
     * @mbggenerated
     */
    private String voteNoitem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.vote_id
     *
     * @return the value of vote.vote_id
     *
     * @mbggenerated
     */
    public Integer getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.vote_id
     *
     * @param voteId the value for vote.vote_id
     *
     * @mbggenerated
     */
    public void setVoteId(Integer voteId) {
        this.voteId = voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.user_name
     *
     * @return the value of vote.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.user_name
     *
     * @param userName the value for vote.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.start_date
     *
     * @return the value of vote.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.start_date
     *
     * @param startDate the value for vote.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.end_date
     *
     * @return the value of vote.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.end_date
     *
     * @param endDate the value for vote.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.joined_number
     *
     * @return the value of vote.joined_number
     *
     * @mbggenerated
     */
    public Integer getJoinedNumber() {
        return joinedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.joined_number
     *
     * @param joinedNumber the value for vote.joined_number
     *
     * @mbggenerated
     */
    public void setJoinedNumber(Integer joinedNumber) {
        this.joinedNumber = joinedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.yes_number
     *
     * @return the value of vote.yes_number
     *
     * @mbggenerated
     */
    public Integer getYesNumber() {
        return yesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.yes_number
     *
     * @param yesNumber the value for vote.yes_number
     *
     * @mbggenerated
     */
    public void setYesNumber(Integer yesNumber) {
        this.yesNumber = yesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.vote_creatstate
     *
     * @return the value of vote.vote_creatstate
     *
     * @mbggenerated
     */
    public Integer getVoteCreatstate() {
        return voteCreatstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.vote_creatstate
     *
     * @param voteCreatstate the value for vote.vote_creatstate
     *
     * @mbggenerated
     */
    public void setVoteCreatstate(Integer voteCreatstate) {
        this.voteCreatstate = voteCreatstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.vote_content
     *
     * @return the value of vote.vote_content
     *
     * @mbggenerated
     */
    public String getVoteContent() {
        return voteContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.vote_content
     *
     * @param voteContent the value for vote.vote_content
     *
     * @mbggenerated
     */
    public void setVoteContent(String voteContent) {
        this.voteContent = voteContent == null ? null : voteContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.vote_yesitem
     *
     * @return the value of vote.vote_yesitem
     *
     * @mbggenerated
     */
    public String getVoteYesitem() {
        return voteYesitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.vote_yesitem
     *
     * @param voteYesitem the value for vote.vote_yesitem
     *
     * @mbggenerated
     */
    public void setVoteYesitem(String voteYesitem) {
        this.voteYesitem = voteYesitem == null ? null : voteYesitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.vote_noitem
     *
     * @return the value of vote.vote_noitem
     *
     * @mbggenerated
     */
    public String getVoteNoitem() {
        return voteNoitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.vote_noitem
     *
     * @param voteNoitem the value for vote.vote_noitem
     *
     * @mbggenerated
     */
    public void setVoteNoitem(String voteNoitem) {
        this.voteNoitem = voteNoitem == null ? null : voteNoitem.trim();
    }
}