package com.example.clubmanage.dao;

import com.example.clubmanage.bean.ActivityMember;
import com.example.clubmanage.bean.ActivityMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_member
     *
     * @mbggenerated
     */
    int countByExample(ActivityMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_member
     *
     * @mbggenerated
     */
    int deleteByExample(ActivityMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer activityMamberid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_member
     *
     * @mbggenerated
     */
    int insert(ActivityMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_member
     *
     * @mbggenerated
     */
    int insertSelective(ActivityMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_member
     *
     * @mbggenerated
     */
    List<ActivityMember> selectByExample(ActivityMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_member
     *
     * @mbggenerated
     */
    ActivityMember selectByPrimaryKey(Integer activityMamberid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_member
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ActivityMember record, @Param("example") ActivityMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_member
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ActivityMember record, @Param("example") ActivityMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityMember record);
}