package com.example.clubmanage.dao;

import com.example.clubmanage.bean.Club;
import com.example.clubmanage.bean.ClubExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    int countByExample(ClubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    int deleteByExample(ClubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer clubId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    int insert(Club record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    int insertSelective(Club record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    List<Club> selectByExample(ClubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    Club selectByPrimaryKey(Integer clubId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Club record, @Param("example") ClubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Club record, @Param("example") ClubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Club record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Club record);
}