package com.example.clubmanage.dao;

import com.example.clubmanage.bean.ClubMember;
import com.example.clubmanage.bean.ClubMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClubMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    int countByExample(ClubMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    int deleteByExample(ClubMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer clubmemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    int insert(ClubMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    int insertSelective(ClubMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    List<ClubMember> selectByExample(ClubMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    ClubMember selectByPrimaryKey(Integer clubmemberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ClubMember record, @Param("example") ClubMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ClubMember record, @Param("example") ClubMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClubMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClubMember record);
}